### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by marcgabe15**

### CODE REVIEW

**Review by kapooramanpreet — COMMENTED** [review]
Regarding the purpose of these templates, are these meant for users or for developers? If these templates are for users, why do we have 'labels' and 'assignees' attributes in the table?  Is this normal practice?

**Comment by marcgabe15** [comment]
> Regarding the purpose of these templates, are these meant for users or for developers? If these templates are for users, why do we have 'labels' and 'assignees' attributes in the table? Is this normal practice?

These are the default templates for users. I will need to add another one just for developers though. Will make another pull request for this

**Comment by kapooramanpreet** [comment]
Yes a user story template would work for developers.

**Review by kapooramanpreet — DISMISSED** [review]
Looks good.

**Review by HamishPierpont — CHANGES_REQUESTED** [review]
Looks great! I'd tweak just a few things:
- The `user_story` headings have a mix of "This kind of title" and "This Kind of Title". I prefer the former because there's less confusion over whether to capitalize words like "the" and "of", but I'm fine with either as long as it's consistent. I think we should use the same capitalization rules for both templates.
- I'd remove lines 4 and 13 from `user_story`.
- The headings in `user_story` are H1 headings with one `#`, but the headings in `pull_request_template` are H2 headings with two `#`s. Can we make them both one `#`?

Thanks for putting these together, Marc :)

**Review by marcgabe15 — COMMENTED** [review]
Changed to h1 tags

**Review by HamishPierpont — APPROVED** [review]
LGTM

**Comment by dhruv2000** [comment]
LGTM

**Review by dhruv2000 — APPROVED** [review]
LGTM

**Pull request merged**
